name: 'Runner setup'
description: 'Setup the runner for the project'
runs:
  using: 'composite'
  steps:
    - uses: pnpm/action-setup@v3
      with:
        version: 9

    - name: Cache for Turbo
      uses: rharkor/caching-for-turbo@v1.5

    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'pnpm'
