name: CI Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Run Lint, Format Check, Build and Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Runner setup
        uses: ./.github/actions/runner-setup

      - name: Install dependencies
        run: pnpm install

      - name: Run lint check
        run: pnpm lint:check

      - name: Run format check
        run: pnpm format:check

      - name: Build the project
        run: pnpm build

      - name: Run JavaScript example tests
        run: pnpm test

      - name: Run TypeScript example tests
        run: pnpm test-ts
